apiVersion: apps/v1
kind: Deployment
metadata:
  name: subtranslate
spec:
  selector:
    matchLabels:
      app: subtranslate
  replicas: 2
  template:
    metadata:
      labels:
        app: subtranslate
    spec:
      containers:
        - name: subtranslate
          image: gcr.io/promising-cairn-386312/subtranslate:latest
          ports:
            - containerPort: 8501
