---
- name: Pull and Run docker image of SubErate
  hosts: all
  tasks:
    - name: pull docker image
      shell: docker pull thugrock/suberate:latest
    - name: run docker image and run tests
      shell: docker run -p 8501:8501 -td --rm thugrock/suberate
    - name: tag and push docker image to GCR
      shell: docker tag thugrock/suberate 'gcr.io/promising-cairn-386312/suberate:latest' && docker push gcr.io/promising-cairn-386312/suberate:latest


